# Generated by Django 5.1.3 on 2024-11-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='precio',
            options={'ordering': ['producto', 'tipo_precio'], 'verbose_name': 'Precio', 'verbose_name_plural': 'Precios'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='precio',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='precio',
            constraint=models.UniqueConstraint(fields=('producto', 'tipo_precio'), name='unique_precio_por_tipo'),
        ),
    ]
