# Generated by Django 5.1.3 on 2024-11-22 18:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_precio_tipo_precio_productoservicio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductoServicio',
            new_name='Catalogo',
        ),
    ]
