# Generated by Django 5.1.3 on 2024-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_productoservicio_catalogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogo',
            options={'ordering': ['nombre'], 'verbose_name': 'Catalogo', 'verbose_name_plural': 'Catalogo'},
        ),
        migrations.AddField(
            model_name='precio',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
