# Generated by Django 5.1.3 on 2024-11-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_catalogo_options_precio_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
