# Generated by Django 5.1.3 on 2024-11-22 19:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_precio_descripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalogo',
            new_name='Item',
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nombre'], 'verbose_name': 'Item', 'verbose_name_plural': 'Item'},
        ),
    ]
