# Generated by Django 5.1.3 on 2024-11-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_catalogo_item_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['nombre'], 'verbose_name': 'Item', 'verbose_name_plural': 'Items'},
        ),
    ]
